Repository Hana1Pick/Hana1Pick-Frontend, pull requests merged in 2024-06, with the labels that each got.

#7 feat: FE 패턴생성 및 비밀번호 값받기, 앱 터치 기능 추가
  src/App.tsx
  src/assets/images/common/PatternBg.png
  src/common/styles/scss/CommonStyle.scss
  src/commonStyle.css
  src/components/pattern/PatternPage.tsx
Labels: feature, 완료

#9 1-feature/handle-account-transfer
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/images/account/CelublogCircleLogo.png
  src/assets/images/account/DepositCircleLogo.png
  src/assets/images/account/MoaClubCircleLogo.png
  src/common/styles/scss/AccountStyle.scss
  src/common/styles/scss/CommonStyle.scss
  src/components/Header.tsx
  src/components/button/CommonBtn.tsx
  src/components/card/AccountCard.tsx
  src/contexts/AccountContextProvider.tsx
  src/pages/account/CashOutPage.tsx
  src/pages/account/CashOutPatternPage.tsx
  src/pages/account/CashOutResultPage.tsx
  src/pages/account/GetAmountPage.tsx
  src/pages/account/SearchAccoutPage.tsx
  src/pages/account/SelectAccountPage.tsx
Labels: feature, 완료

#17 8 feature/moaclub create
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/common/backicon.png
  src/assets/images/common/checkicon.png
  src/assets/images/common/deleteicon.png
  src/assets/images/common/righticon.png
  src/assets/images/moaclub/moaclub-banner.png
  src/assets/images/moaclub/moaclub-complete.png
  src/common/styles/scss/CommonStyle.scss
  src/contexts/MoaclubContextProvider.tsx
  src/layouts/MoaclubHeader1.tsx
  src/layouts/MoaclubHeader2.tsx
  src/pages/moaclub/MoaclubComplete.tsx
  src/pages/moaclub/MoaclubCreatePage.tsx
  src/pages/moaclub/MoaclubOpening.tsx
  src/pages/moaclub/MoaclubPattern.tsx
  src/pages/moaclub/MoaclubSelectAcc.tsx
  src/pages/moaclub/MoaclubStyle.scss
  src/pages/moaclub/Picker.tsx
  src/type/commonType.tsx
  tsconfig.json
Labels: feature

#15 12 feature/celub account list
  src/App.tsx
  src/assets/images/celub/CelubBack.png
  src/assets/images/celub/celubAcc.png
  src/assets/images/celub/heart.png
  src/commonStyle.css
  src/components/pattern/PatternPage.tsx
  src/pages/celublog/CelubAccountList.tsx
  src/pages/celublog/CelubComplete.tsx
  src/pages/celublog/CelubDetail.tsx
  src/pages/celublog/CelubWithdraw.tsx
  src/pages/celublog/CelublogStyle.scss
  src/type/commonType.tsx
Labels: feature, 완료

#20 feature/create deposit
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/assets/images/deposit/BlackArrow.png
  src/assets/images/deposit/Calendar.png
  src/assets/images/deposit/CreateComplete.png
  src/assets/images/deposit/CreateDeposit.jpg
  src/assets/images/deposit/WhiteArrow.png
  src/common/styles/scss/CommonStyle.css
  src/components/Header.tsx
  src/components/button/CommonBtn.tsx
  src/index.tsx
  src/pages/deposit/DepositComplete.tsx
  src/pages/deposit/DepositCreation1.tsx
  src/pages/deposit/DepositCreation2.tsx
  src/pages/deposit/DomesticAuth.tsx
  src/pages/deposit/PatternPassword.tsx
  src/pages/deposit/UserAgree.tsx
  src/pages/deposit/style.css
  src/pages/deposit/useScript.tsx
  src/type/commonType.tsx
  tsconfig.json
Labels: feature

#24 11 feature/kakao login
  src/index.tsx
  src/pages/deposit/DepositCreation1.tsx
  src/pages/deposit/DepositCreation2.tsx
  src/pages/user/login/LoginHandeler.tsx
Labels: fix

#26 25-featurecreate-depositaccount
  src/common/styles/scss/CommonStyle.scss
  src/components/button/CommonBtn.tsx
  src/pages/deposit/PatternPassword.tsx
  src/pages/deposit/UserAgree.tsx
Labels: feature

#29 28-refactor/handle-transfer-limit
  src/pages/account/CashOutPatternPage.tsx
Labels: 완료, refactor
